---
ignored:
  # Warning: Use the -y switch to avoid manual input dnf install -y <package>
  # https://github.com/hadolint/hadolint/wiki/DL3038
  # Reason: We set `assumeyes=True` in dnf.conf in our base image
  - DL3038

  # Warning: Specify version with dnf install -y <package>-<version>
  # https://github.com/hadolint/hadolint/wiki/DL3041
  # Reason: It's good advice, but we're not set up to pin versions just yet
  - DL3041
