---
# All defaults or options can be checked here:
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 9999
  # Number of characters for headings
  heading_line_length: 9999
  # Number of characters for code blocks
  code_block_line_length: 9999

# MD033/no-inline-html
MD033:
  allowed_elements: [h1, img, p]

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true

# MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading
MD041: false # Github issues and PRs already have titles, and H1 is enormous in the description box.
