---
exclude: ^(Cargo\.nix|crate-hashes\.json|nix/.*)$

default_language_version:
  node: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # 6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key

  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 1c9ca2b643ee15722178c1350501aabb024dd6f3 # 0.19.9
    hooks:
      - id: cargo-deny
        args: ["--all-features", "check", "advisories", "bans", "licenses", "sources"]

  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7 # 1.37.1
    hooks:
      - id: yamllint
        args: ["--strict"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: a4d5d37e66ebcd6b3705204a1d6dbb56dea66338 # 0.49.0
    hooks:
      - id: markdownlint
        types: [text]
        files: \.md(\.j2)*$

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d # 0.11.0
    hooks:
      - id: shellcheck
        args: ["--severity=info"]
        # Temporarily needed until all getting_started.sh.j2 scripts are made non-executable.
        # As long as they are, prek will treat them as shell scripts and so this hook will fail.
        # pre-commit behaves differently apparently and doesn't pass .j2 files to this hook.
        exclude: \.j2$

  # WARNING (@NickLarsenNZ): Nix users need to install ruff first.
  # If you do not, you will need to delete the cached ruff binary shown in the
  # error message
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56 # 0.15.20
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # 1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/hadolint/hadolint
    rev: 57e1618d78fd469a92c1e584e8c9313024656623 # 2.14.0
    hooks:
      - id: hadolint

  - repo: local
    hooks:
      - id: regenerate-charts
        name: regenerate-charts
        language: system
        entry: make regenerate-charts
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: \.rs$|Cargo\.(toml|lock)

      - id: regenerate-nix
        name: regenerate-nix
        language: system
        entry: make regenerate-nix
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: Cargo\.lock

      - id: check-readme
        name: check-readme
        language: system
        entry: make render-readme
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: .readme

      - id: cargo-doc
        name: cargo-doc
        language: system
        entry: cargo doc --no-deps --document-private-items
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: \.rs$|Cargo\.(toml|lock)

      - id: cargo-test
        name: cargo-test
        language: system
        entry: cargo test
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: \.rs$|Cargo\.(toml|lock)

      - id: cargo-rustfmt
        name: cargo-rustfmt
        language: system
        entry: cargo +nightly-2026-07-01 fmt --all -- --check
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: \.rs$

      - id: cargo-clippy
        name: cargo-clippy
        language: system
        entry: cargo clippy --all-targets -- -D warnings
        stages: [pre-commit, pre-merge-commit]
        pass_filenames: false
        files: \.rs$
