---
extends: default

ignore: |
  deploy/helm/**/templates

rules:
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1  # Needed due to https://github.com/adrienverge/yamllint/issues/443
  indentation:
    indent-sequences: consistent
  comments-indentation: disable # This is generally useless and interferes with commented example values
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0
