---
- name: Delete target dir for tests if it exists
  file:
    path: "{{ work_dir }}/tests"
    state: absent

- name: Create target dir for tests
  file:
    path: "{{ work_dir }}/tests"
    state: directory

- name: Create test scenarios from dimensions file
  ansible.builtin.script: generate_tests.py -i {{ test_dir }}/test-definition.yaml -o {{ work_dir }}/dimensions.yaml

- name: Read test definitions
  include_vars:
    file: "{{ test_dir }}/test-definition.yaml"
    name: testinput

- name: Read test scenario definitions
  include_vars:
    file: "{{ work_dir }}/dimensions.yaml"
    name: testdefinition

- name: Create kuttl-test.yaml
  template:
      src: "{{ test_dir}}/kuttl-test.yaml.j2"
      mode: "preserve"
      dest: "{{ work_dir }}/kuttl-test.yaml"

- name: Create test scenarios
  include_tasks: create_scenario.yaml
  loop: "{{ testdefinition.tests }}"
  loop_control:
    loop_var: test_scenario

