= Job Dependencies
:page-aliases: job_dependencies.adoc

== Overview

IMPORTANT: With the platform release 23.4.1 and Apache Spark 3.3.x (and all previous releases), dynamic provisioning of dependencies using the Spark `packages` field doesn't work. This is a known problem with Spark and is tracked https://github.com/stackabletech/spark-k8s-operator/issues/141[here].

The container images provided by Stackable include Apache Spark and PySpark applications and libraries. In addtion they include commonly used libraries to connect to storage systems supporting the `hdfs://`, `s3a://` and `abfs://` protocols. These systems are commonly used to store data processed by Spark applications.

Sometimes the applications need to integrate with additional systems or use processing algorithms not included in the Apache Spark distribution. This guide explains how users can provision their Spark jobs with additional dependencies to support these requirements.

== Dependency provisioning

There are multiple ways to submit Apache Spark jobs with external dependencies. Each has its own advantages and disadvantages and the choice of one over the other depends on existing technical and managerial constraints.

To provision job dependencies in their workloads, users have to construct their `SparkApplication` with one of the following dependency specifications:

- Custom Spark images
- Dependency volumes
- Maven/Java packages
- Python packages

The following table provides a high level overview of the relevant aspects of each method.

|===
|Dependency specification |Job image size |Reproduciblity |Dev-op cost

|Custom Spark images
|Large
|Guaranteed
|Medium to High

|Dependency volumes
|Small
|Guaranteed
|Small to Medium

|Maven/Java packages
|Small
|Not guaranteed
|Small

|Python packages
|Small
|Not guaranteed
|Small
|===

=== Custom Spark images

With this method, users submit a `SparkApplication` for which the `sparkImage` refers to the full custom image name. It is recommended the users base their image on one of the Stackable images to ensure compatibility with the Stackable operator.

Below is an example of a custom image that includes a JDBC driver:

[source, Dockerfile]
----
FROM docker.stackable.tech/stackable/spark-k8s:3.5.1-stackable24.3.0 # <1>

RUN curl --fail -o /stackable/spark/jars/postgresql-42.6.0.jar "https://jdbc.postgresql.org/download/postgresql-42.6.0.jar"
----

<1> Start from an existing Stackable image.

And the following snippet showcases an application that uses the custom image:

[source, yaml]
----
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: spark-jdbc
spec:
  sparkImage:
    custom: "docker.stackable.tech/sandbox/spark-k8s:3.5.1-stackable0.0.0-dev" # <1>
    productVersion: "3.5.1" # <2>
    pullPolicy: IfNotPresent # <3>
...
----
<1> Name of the custom image.
<2> Apache Spark version. Needed for the operator to take the correct actions.
<3> Optional. Defaults to `Always`.

=== Dependency volumes

With this method, the user provisions the job dependencies from a `PersistentVolume` as shown in this example:

[source,yaml]
----
include::example$example-sparkapp-pvc.yaml[]
----
<1> Job artifact located on S3.
<2> Job main class
<3> Spark dependencies: the credentials provider (the user knows what is relevant here) plus dependencies needed to access external resources (in this case, in s3, accessed without credentials)
<4> the name of the volume mount backed by a `PersistentVolumeClaim` that must be pre-existing
<5> the path on the volume mount: this is referenced in the `sparkConf` section where the extra class path is defined for the driver and executors

NOTE: The Spark operator has no control over the contents of the dependency volume. It is the responsibility of the user to make sure all required dependencies are installed in the correct versions.

A `PersistentVolumeClaim` and the associated `PersistentVolume` can be defined like this:

[source,yaml]
----
include::example$example-pvc.yaml[]
----
<1> Reference to a `PersistentVolume`, defining some cluster-reachable storage
<2> The name of the `PersistentVolumeClaim` that references the PV
<3> Defines a `Volume` backed by the PVC, local to the Custom Resource
<4> Defines the `VolumeMount` that is used by the Custom Resource


=== Maven packages

The last and most flexible way to provision dependencies is to use the built-in `spark-submit` support for Maven package coordinates.

The snippet below showcases how to add Apache Iceberg support to a Spark (version 3.4.x) application.

[source,yaml]
----
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: spark-iceberg
spec:
  sparkConf:
    spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    spark.sql.catalog.spark_catalog: org.apache.iceberg.spark.SparkSessionCatalog
    spark.sql.catalog.spark_catalog.type: hive
    spark.sql.catalog.local: org.apache.iceberg.spark.SparkCatalog
    spark.sql.catalog.local.type: hadoop
    spark.sql.catalog.local.warehouse: /tmp/warehouse
  deps:
    packages:
      - org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.1 # <1>
...
----

<1> Maven package coordinates for Apache Iceberg. This is downloaded from the Manven repository and made available to the Spark application.

IMPORTANT: Currently it's not possible to provision dependencies that are loaded by the JVM's (system class loader)[https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ClassLoader.html#getSystemClassLoader()]. Such dependencies include JDBC drivers. If you need access to JDBC sources from your Spark application, consider building your own custom Spark image as shown above.

=== Python packages

When submitting PySpark jobs, users can specify additional Python requirements that are installed before the driver and executor pods are created.

Here is an example:

[source,yaml]
----
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: pyspark-report
spec:
  mainApplicationFile: /app/run.py # <1>
  deps:
    requirements:
      - tabulate==0.8.9  # <3>
... 
----

<1> The main application file. In this example it is assumed that the file is part of a custom image.
<2> A Python package that is used by the application and installed when the application is submitted.


