---
apiVersion: batch/v1
kind: Job
metadata:
  name: assert-pvc-jars
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: job-deps
          persistentVolumeClaim:
            claimName: pvc-ksv
      containers:
        - name: assert-pvc-jars
          image: oci.stackable.tech/sdp/tools:1.0.0-stackable0.0.0-dev
          env:
            - name: DEST_DIR
              value: "/dependencies/jars"
          command: ["bash", "-x", "-c", "ls -ltr $DEST_DIR"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: job-deps
              mountPath: /dependencies
