---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ksv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /kind-shared-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ksv
spec:
  volumeName: pv-ksv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: aws-deps
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: job-deps
          persistentVolumeClaim:
            claimName: pvc-ksv
      initContainers:
      - name: dest-dir
        image: docker.stackable.tech/stackable/tools:0.2.0-stackable0
        env:
          - name: DEST_DIR
            value: "/stackable/spark/dependencies/jars"
        command: ['bash', '-x', '-c', 'mkdir -p $DEST_DIR && chown stackable:stackable ${DEST_DIR} && chmod -R a=,u=rwX ${DEST_DIR}']
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: job-deps
            mountPath: /stackable/spark/dependencies
      containers:
      - name: aws-deps
        image: docker.stackable.tech/stackable/tools:0.2.0-stackable0
        env:
          - name: DEST_DIR
            value: "/stackable/spark/dependencies/jars"
          - name: AWS
            value: "1.11.375"
          - name: HADOOP
            value: "3.2"
        command: ["bash", '-x', '-c', 'curl -L  https://search.maven.org/remotecontent?filepath=org/apache/hadoop/hadoop-aws/${HADOOP}.0/hadoop-aws-${HADOOP}.0.jar -o ${DEST_DIR}/hadoop-aws-${HADOOP}.0.jar && curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS}/aws-java-sdk-bundle-${AWS}.jar -o ${DEST_DIR}/aws-java-sdk-bundle-${AWS}.jar']
        volumeMounts:
          - name: job-deps
            mountPath: /stackable/spark/dependencies
