---
apiVersion: v1
kind: Service
metadata:
  name: minio-mc
  labels:
    app: minio-mc
spec:
  clusterIP: None
  selector:
    app: minio-mc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-mc
  labels:
    app: minio-mc
spec:
  replicas: 1
  serviceName: "minio-mc"
  selector:
    matchLabels:
      app: minio-mc
  template:
    metadata:
      labels:
        app: minio-mc
    spec:
      containers:
        - name: minio-mc
          image: docker.io/bitnamilegacy/minio:2024-debian-12
          stdin: true
          tty: true
