---
apiVersion: v1
data:
  properties.yaml: |
    ---
    # Not used. Kept for compatibilty with Dockerfile.
    version: 0.1.0
    spec:
      units: []
    properties: []
kind: ConfigMap
metadata:
  name: spark-k8s-operator-configmap
  labels:
    app.kubernetes.io/name: spark-k8s-operator
    app.kubernetes.io/instance: spark-k8s-operator
    app.kubernetes.io/version: "0.5.0-nightly"
