---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: spark-k8s-operator
spec:
  annotations:
    support: stackable.tech
    olm.properties: '[]'

    # The following affect how the package is indexed at OperatorHub.io:
    # https://operatorhub.io/?category=Database
    # https://sdk.operatorframework.io/docs/advanced-topics/operator-capabilities/operator-capabilities/
    categories: "Big Data"
    capabilities: Full Lifecycle
    description: Apache Spark for the Stackable platform


  description: Stackable operator for Apache Spark
  displayName: Apache Spark Operator
  keywords:
    - spark
  maintainers:
    - email: info@stackable.tech
      name: Stackable GmbH
  maturity: stable
  provider:
    name: Stackable GmbH
    url: https://stackable.tech
  version: 0.5.0-nightly
  minKubeVersion: 1.20.0

  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces

  customresourcedefinitions:
    owned:
      # a list of CRDs that this operator owns
      # name is the metadata.name of the CRD (which is of the form <plural>.<group>)
      - name: sparkapplications.spark.stackable.tech
        # version is the spec.versions[].name value defined in the CRD
        version: v1alpha1
        # kind is the CamelCased singular value defined in spec.names.kind of the CRD.
        kind: SparkApplication
        # human-friendly display name of the CRD for rendering in graphical consoles (optional)
        displayName: Spark Application
        # a short description of the CRDs purpose for rendering in graphical consoles (optional)
        description: Spark Application

  install:
    # strategy indicates what type of deployment artifacts are used
    strategy: deployment
    # spec for the deployment strategy is a list of deployment specs and required permissions - similar to a pod template used in a deployment
    spec:
      clusterPermissions:
        - serviceAccountName: spark-k8s-operator-serviceaccount
          rules:
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - persistentvolumeclaims
              verbs:
                - list
            - apiGroups:
                - ""
              resources:
                - pods
                - configmaps
                - secrets
                - services
                - endpoints
                - serviceaccounts
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - create
                - delete
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - get
            - apiGroups:
                - events.k8s.io
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - spark.stackable.tech
              resources:
                - sparkapplications
              verbs:
                - get
                - list
                - patch
                - watch
            - apiGroups:
                - spark.stackable.tech
              resources:
                - sparkapplications/status
              verbs:
                - patch
            - apiGroups:
                - s3.stackable.tech
              resources:
                - s3connections
                - s3buckets
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
              verbs:
                - bind
              resourceNames:
                - spark-k8s-clusterrole
            - apiGroups:
                - security.openshift.io
              resources:
                - securitycontextconstraints
              resourceNames:
                - anyuid
              verbs:
                - use

      deployments:
        - name: spark-k8s-operator-deployment
          spec:
            replicas: 1
            strategy:
              type: Recreate
            selector:
              matchLabels:
                app.kubernetes.io/name: spark-k8s-operator
                app.kubernetes.io/instance: spark-k8s-operator
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: spark-k8s-operator
                  app.kubernetes.io/instance: spark-k8s-operator
              spec:
                serviceAccountName: spark-k8s-operator-serviceaccount
                securityContext:
                  readOnlyRootFilesystem: false
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                containers:
                  - name: spark-k8s-operator
                    securityContext:
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: false
                      capabilities:
                        drop:
                          - ALL
                    image: "docker.stackable.tech/stackable/spark-k8s-operator:0.5.0-nightly"
                    imagePullPolicy: IfNotPresent
                    resources: {}
                    volumeMounts:
                      - mountPath: /etc/stackable/spark-k8s-operator/config-spec
                        name: config-spec
                volumes:
                  - name: config-spec
                    configMap:
                      name: spark-k8s-operator-configmap
