---
dependencies:
  - type: olm.package
    value:
      packageName: commons-operator-package
      version: "23.4.0"
  - type: olm.package
    value:
      packageName: secret-operator-package
      version: "23.4.0"
