---
apiVersion: v1
kind: PersistentVolume  # <1>
metadata:
  name: pv-ksv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /some-host-location
---
apiVersion: v1
kind: PersistentVolumeClaim # <2>
metadata:
  name: pvc-ksv
spec:
  volumeName: pv-ksv # <3>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job # <4>
metadata:
  name: aws-deps
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: job-deps
          persistentVolumeClaim:
            claimName: pvc-ksv # <5>
      containers:
        - name: aws-deps
          volumeMounts:
            - name: job-deps
              mountPath: /stackable/spark/dependencies
