---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: example-sparkapp-pvc
  namespace: default
spec:
  sparkImage:
    productVersion: 3.5.7
  mode: cluster
  mainApplicationFile: s3a://my-bucket/app.jar # <1>
  mainClass: org.example.App # <2>
  sparkConf: # <3>
    "spark.driver.extraClassPath": "/dependencies/jars/*"
    "spark.executor.extraClassPath": "/dependencies/jars/*"
  volumes:
    - name: job-deps # <4>
      persistentVolumeClaim:
        claimName: pvc-ksv
  job:
    config:
      volumeMounts:
        - name: job-deps
          mountPath: /dependencies # <5>
  driver:
    config:
      volumeMounts:
        - name: job-deps
          mountPath: /dependencies # <6>
  executor:
    replicas: 3
    config:
      volumeMounts:
        - name: job-deps
          mountPath: /dependencies # <7>
