---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkHistoryServer
metadata:
  name: spark-history
spec:
  image:
    productVersion: 3.3.0
    stackableVersion: 0.0.0-dev
  logFileDirectory:  # <1>
    s3:
      prefix: eventlogs/  # <2>
      bucket:  # <3>
        inline:
          bucketName: spark-logs
          connection:
            inline:
              host: test-minio
              port: 9000
              accessStyle: Path
              credentials:
                secretClass: history-credentials-class
  sparkConf:  # <4>
  nodes:
    roleGroups:
      default:
        replicas: 1  # <5>
        config:
          cleaner: true # <6>
