---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: spark-pi
spec:
  version: "1.0"
  sparkImage:
    productVersion: 3.3.0 # <1>
  mode: cluster
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: /stackable/spark/examples/jars/spark-examples.jar # <2>
  executor:
    instances: 3
